inherit_gem:
 rubocop-rails:
   - config/rails.yml

AllCops:
 TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - '**/bin/*'
    - '**/db/schema.rb'