dist: trusty
language: ruby
rvm:
  - 2.3.1
  - 2.4.2

branches:
  only:
    - master

addons:
  chrome: stable
  postgresql: '9.5'

cache:
  bundler: true

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox

before_script:
  - psql -c 'create database cdx_dummy_test;' -U postgres
  - bin/rails db:migrate RAILS_ENV=test

script:
  - bundle exec rspec --format doc

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
