sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.1
  - 2.4.2

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  postgresql: '9.5'

cache:
  bundler: true

env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta

before_script:
  - psql -c 'create database cdx_dummy_test;' -U postgres
  - bin/rails db:migrate RAILS_ENV=test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - bundle exec rspec --format doc

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
