language: ruby
rvm:
  - 2.3.1

branches:
  only:
    - master

addons:
  postgresql: '9.5'

cache:
  bundler: true

before_script:
  - psql -c 'create database cdx_dummy_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rspec --format doc